la_netscouade_angular_demo:
    resource: "@LaNetscouadeAngularDemoBundle/Controller/"
    type:     annotation
    prefix:   app

la_netscouade_api_demo_bundle:
    resource: LaNetscouade\ApiDemoBundle\Controller\CocktailController
    type:     rest
    options:
        expose: true
    prefix: api

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"
